print("===PROGRAM MENGHITUNG NILAI AKHIR MAHASISWA===")
print("----------------------------------------------")
print()

nama=input("masukkan nama :")
nim=input("masukkan NIM :")
matkul=input("masukkan mata kuliah :")
smtr=input("masukkan semester :")

print("----------------------------------------")
print()
print("KETERANGAN :\n1.Tugas dikali 20% \n2.UTS dikali 40% \n3.UAS dikali 40%")
print()
tugas=float(input("masukkan nilai tugas (1-100) :"))
UTS=float(input("masukkan nilai UTS (1-100) :"))
UAS=float(input("masukkan nilai UAS (1-100) :"))
hasil_akhir=(tugas * 0.2) + (UTS * 0.4) + (UAS * 0.4)
print()

print("===== Hasil Perhitungan =====")
print("Nama :",nama)
print("NIM :",nim)
print("Mata Kuliah :",matkul)
print("Semester :",smtr)
print()
print("Nilai Tugas :",tugas)
print("Nilai UTS :",UTS)
print("Nilai UAS :",UAS)
print()
print("Nilai Akhir :",hasil_akhir)
